#pragma shader_stage(compute)
#extension GL_EXT_nonuniform_qualifier : require
#extension GL_EXT_shader_8bit_storage : require
#extension GL_EXT_control_flow_attributes : require

#define WC_DEBUG 0

#if WC_DEBUG

#extension GL_EXT_debug_printf : enable
#define printf debugPrintfEXT

#endif

layout(local_size_x = 4, local_size_y = 4) in;
layout(binding = 9, rgba32f) restrict writeonly uniform image2D o_Image;
layout(binding = 10, set = 0) uniform sampler2D u_Textures[];

#define MATERIAL_PROPERTY(x, uv) x >= 0.f ? x : texture(u_Textures[int(abs(x))], uv).r

layout (push_constant) uniform Scene
{
	vec3 cameraPos;
	uint u_NumLights;
    vec3 lower_left_corner;
    uint u_NumDrawCommands;
    vec3 horizontal;
    uint _pad;
    vec3 vertical;
};

#include <sky.glsl>
#include <Geometry.glsl>
#include <pbrUtil.glsl>

vec3 rayTrace(inout vec3 refRayOrigin, inout vec3 refRayDirection) {
	vec3 color = vec3(0.f);
    vec3 invRayDirection = 1.f / refRayDirection;
    // Intersection info
    HitInfo hitInfo = intersect(refRayOrigin, refRayDirection, invRayDirection);

    if (hitInfo.isHit) {
        vec2 texCoords = vec2(0.f);

        if (hitInfo.hitCube) {
            
            texCoords = hitInfo.uvw.xy;
        }
        else{
            hitInfo.p = refRayOrigin + hitInfo.minT * refRayDirection;
            texCoords = rtLerp(hitInfo.uvw, GetVertex(hitInfo.shapeHit + 1, hitInfo.cmd).TexCoords, 
            GetVertex(hitInfo.shapeHit + 2, hitInfo.cmd).TexCoords, GetVertex(hitInfo.shapeHit, hitInfo.cmd).TexCoords);		

        }
		vec3 v = -refRayDirection;
		vec3 n = hitInfo.N;

	    float NoV = max(dot(n, v), 1e-4);

        vec3 albedo = texture(u_Textures[materials[hitInfo.materialID].albedo], texCoords).rgb;
	    float metallic = MATERIAL_PROPERTY(materials[hitInfo.materialID].metallic, texCoords);
        float perceptualRoughness = max(MATERIAL_PROPERTY(materials[hitInfo.materialID].roughness, texCoords), MIN_PERCEPTUAL_ROUGHNESS);
		float reflectance = MATERIAL_PROPERTY(materials[hitInfo.materialID].reflectance, texCoords);
		float emissive = MATERIAL_PROPERTY(materials[hitInfo.materialID].emissive, texCoords);

		if (emissive > 0.f) return albedo * (emissive + 1.f);

		vec3 diffuseColor = (1.0 - metallic) * albedo;
		
        float roughness = max(perceptualRoughness * perceptualRoughness, MIN_ROUGHNESS);

		vec3 F0 = 0.16 * reflectance * reflectance * (1.0 - metallic) + albedo * metallic;

	    // reflectance equation
	    vec3 Lo = vec3(0.f);
	    for (uint i = 0; i < u_NumLights; i++)
	    {
	    	// calculate per-light radiance
	    	vec3 radiance = lights[i].color;
	    	float radius = lights[i].radius;

	    	vec3 L = lights[i].vector;
	    	if (radius > 0.f){
	    		L -= hitInfo.p;
	    		radiance /= dot(L, L) * radius; // radiance / attenuation
	    		L = normalize(L);
	    	}

	    	vec3 H = normalize(L + v);

	    	float NoL = saturate(dot(n, L));
	    	float NoH = saturate(dot(n, H));
	    	float LoH = saturate(dot(L, H));
	    	float HoV = saturate(dot(H, v));

			float D = D_GGX(roughness, NoH, H);
			float V = V_SmithGGXCorrelated(roughness, NoV, NoL);
			vec3 F = fresnelSchlick(LoH, F0);
			vec3 Fd = diffuseColor * Fd_Burley(roughness, NoV, NoL, LoH);
			vec3 Fr = (D * V) * F;

			Lo += (lights[i].intensity * radiance) * NoL * (Fd + Fr);
	    }

		vec3 ambientColor = vec3(0.03f);
	    vec3 ambient = ambientColor * albedo;

	    color = ambient + Lo;
    }    
    else 
        {
			vec3 color1 = clamp(getNebula(refRayOrigin, refRayDirection, 1.0, 0.5) * 1.5, 0.0, 1.0) * vec3(0.0, 0.0, 1.0);
    		vec3 color2 = clamp(getNebula(refRayOrigin, refRayDirection, 2.0, 0.5) * 1.5, 0.0, 1.0) * vec3(0.0, 1.0, 1.0);
					    
     		vec3 color3 = clamp(getNebula(refRayOrigin, -refRayDirection, 2.0, 0.5) * 0.9, 0.0, 1.0) * vec3(1.0, 0.0, 0.0);
    		vec3 color4 = clamp(getNebula(refRayOrigin, -refRayDirection, 3.0, 0.5) * 0.7, 0.0, 1.0) * vec3(1.0, 1.0, 0.0);
					    
     		vec3 color5 = clamp(getNebula(refRayOrigin, refRayDirection.yxz + refRayDirection.yzx, 1.5, 0.5) * 0.9, 0.0, 1.0) * vec3(0.0, 1.0, 0.0);
    		vec3 color6 = clamp(getNebula(refRayOrigin, refRayDirection.yxz + refRayDirection.yzx, 2.5, 0.5) * 0.7, 0.0, 1.0) * vec3(0.333, 0.333, 0.333);
		
    		vec3 colorStars = clamp(getStars(refRayOrigin, refRayDirection, 0.9), 0.0, 1.0);
			
			float mixer = 0.f;
			vec3 daySky = computeIncidentLight(vec3(refRayOrigin.x, earthRadius + refRayOrigin.y, refRayOrigin.z), refRayDirection, mixer);
			vec3 nightSky = color1 + color2 + color3 + color4 + color5 + color6 + colorStars;
			color = mix(daySky, nightSky, mixer);
		}


	
    return color;
}

vec3 Render(const in vec3 rayDirection) {
	vec3 refRayOrigin = cameraPos;
	vec3 refRayDirection = rayDirection;
	vec3 color = rayTrace(refRayOrigin, refRayDirection);

	return color;
}

void main()
{
    ivec2 invocID = ivec2(gl_GlobalInvocationID.xy);
    vec2 uv = (invocID / vec2(imageSize(o_Image)));
    uv.y = 1.f - uv.y;
	vec3 result = Render(normalize(lower_left_corner + uv.x * horizontal + uv.y * vertical - cameraPos));

    imageStore(o_Image, invocID, vec4(result, 1.f));
}