RenderDistance: 1
MouseSensitivity: 5
InvertMouse: false
Bloom: true
BloomThreshold: 0.800000012
BloomKnee: 0.5
ColorBlindMode: false
FPSCap: 0
WindowMode: 0
WindowResolution: 2
ToneMapFunction: 0
maxBounceCount: 1
raysPerPixel: 1