right =  "assets/textures/misc/skybox/sun.png"
left =   "assets/textures/misc/skybox/sun.png"
top =    "assets/textures/misc/skybox/sun.png"
bottom = "assets/textures/misc/skybox/sun.png"
front =  "assets/textures/misc/skybox/sun.png"
back =   "assets/textures/misc/skybox/sun.png"
shaderPath = "shaderpacks/default/skybox.glsl"