right =  "assets/skybox/skybox4/right.png"
left =   "assets/skybox/skybox4/left.png"
top =    "assets/skybox/skybox4/top.png"
bottom = "assets/skybox/skybox4/bottom.png"
front =  "assets/skybox/skybox4/front.png"
back =   "assets/skybox/skybox4/back.png"
shaderPath = "shaderpacks/default/skybox.glsl"